import { checkNewPassword, passwordAttemptsLockedMs, registerPasswordFailure, clearPasswordFailures } from "../src/lib/password-policy";
let bad = 0;
const t = (name: string, got: unknown, want: unknown) => { const ok = JSON.stringify(got) === JSON.stringify(want); if (!ok) bad++; console.log(ok ? "ok  " : "FAIL", name, ok ? "" : `got=${JSON.stringify(got)} want=${JSON.stringify(want)}`); };
const email = "everton@banguelas.com.br";
t("curta", checkNewPassword("abc123", { email }) !== null, true);
t("só letras", checkNewPassword("abcdefghijkl") !== null, true);
t("só números", checkNewPassword("1234567890123") !== null, true);
t("repetida", checkNewPassword("aaaaaaaaaaaa") !== null, true);
t("contém e-mail", checkNewPassword("everton2026Ab", { email }) !== null, true);
t("igual à atual", checkNewPassword("Senhaboa1234", { email, current: "Senhaboa1234" }) !== null, true);
t("acima de 72 bytes", checkNewPassword("a1".repeat(40)) !== null, true);
t("válida", checkNewPassword("Cafe-com-leite-42", { email, current: "outra" }), null);
t("válida com acento", checkNewPassword("açaí-gelado-2026"), null);
const u = "u1"; let now = 1_000_000;
t("sem bloqueio", passwordAttemptsLockedMs(u, now), 0);
for (let i = 0; i < 4; i++) registerPasswordFailure(u, now);
t("4 erros ainda livre", passwordAttemptsLockedMs(u, now), 0);
registerPasswordFailure(u, now);
t("5º erro bloqueia", passwordAttemptsLockedMs(u, now) > 0, true);
t("libera após 15 min", passwordAttemptsLockedMs(u, now + 15 * 60_000 + 1), 0);
clearPasswordFailures(u); t("limpa no acerto", passwordAttemptsLockedMs(u, now), 0);
process.exit(bad ? 1 : 0);
